### ISSUE TITLE
Allow specifying multiple files to run on

### ISSUE THREAD

**Issue by mheinzel** [vaclavsvejcar/headroom#43]
This would allow things like `headroom run $(git ls-files)` (alleviating the need for #42). Maybe targets could also be piped to Headroom?

**Comment by vaclavsvejcar** [comment]
This is kinda already supported by Headroom, the `-s|--source-path=PATH` options can be repeated (as well as `-t|--template-path=PATH` and `-v|--variable="KEY=VALUE"`) so you can use something as

```
$ headroom run -s path/to/file_or_dir1 -s path/to/file_or_dir2 ...
```

So if you're able to transform the result of `git ls-files` into this format, it could serve as temporary workaround for #42.

**Comment by mheinzel** [comment]
Ah, cool. It's not quite as convenient, but should work. Thanks!

**Comment by vaclavsvejcar** [comment]
Good! Guess I can close this one for now but if you feel that the cli options regarding this should be implemented differently, feel free to create issue with the proposal.
