### ISSUE TITLE
Only touch files if they actually changed

### ISSUE THREAD

**Issue by mheinzel** [vaclavsvejcar/headroom#44]
Instead of always writing the result of dropping/adding/replacing the header, it should only be written if it's different from the previous file content. This avoids changing the timestamp, which would for example trigger unnecessary rebuilds when using Makefiles.

**Comment by vaclavsvejcar** [comment]
Valid point, guess this can be considered as bug, will fix this one in next bugfix release.

**Comment by vaclavsvejcar** [comment]
Fixed, will be released as part of the upcoming version [0.2.1.0](https://github.com/vaclavsvejcar/headroom/milestone/5).
