### ISSUE TITLE
Add --check-headers command

### ISSUE THREAD

**Issue by mheinzel** [vaclavsvejcar/headroom#45]
It would work similarly to `--replace-headers`, but if any of the file's contents changed (#44), Headroom would fail with an error message listing all files that changed.

This would be useful to run in CI to make sure the correct license headers are added to all files.

**Comment by vaclavsvejcar** [comment]
Sounds good, guess this one will be pretty straightforward to implement and can be part of the upcoming [version 0.2.2.0](https://github.com/vaclavsvejcar/headroom/milestone/6).

**Comment by vaclavsvejcar** [comment]
@mheinzel This feature is now implemented in `master` and can be selected using the `headroom run -c` or `headroom run --check-headers` command. It ends execution with return code `1` in case that any source file contains outdated license header.  I'll release it to _Hackage_ with upcoming version, after I'll do some more testing.

**Comment by vaclavsvejcar** [comment]
@mheinzel Final version `0.2.2.0` has been released to [hackage](https://hackage.haskell.org/package/headroom).
