### ISSUE TITLE
Will not build with GHC 8.10

### ISSUE THREAD

**Issue by kozross** [vaclavsvejcar/headroom#47]
This is due to the way ``text`` is depended on:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: headroom-0.2.1.0 (user goal)
[__1] next goal: text (dependency of headroom)
[__1] rejecting: text-1.2.3.2/installed-1.2.3.2 (conflict: headroom =>
text>=1.2.4.0 && <1.3)
[__1] trying: text-1.2.4.0
[__2] next goal: base (dependency of headroom)
[__2] rejecting: base-4.14.0.0/installed-4.14.0.0 (conflict: text =>
ghc-prim>=0.2 && <0.6, base => ghc-prim==0.6.1/installed-0.6.1)
[__2] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: base, headroom, text)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: headroom, text, base
```

**Comment by vaclavsvejcar** [comment]
Hi, thanks for reporting this. Honestly, I haven't tried building Headrooom with GHC 8.10, as the main intent was to use Stack to build it so it's tested mainly with GHC 8.8. Anyway, it would be nice to have it working under 8.10. Do you know what exactly needs to be corrected in order to pass the build?

**Comment by kozross** [comment]
The problem is ``text>=1.2.4.0`` as a requirement, as that release does not support GHC 8.10. However, ``1.2.3.2`` _does_, and as far as I'm aware, has the same feature set.

**Comment by vaclavsvejcar** [comment]
Guess this https://github.com/haskell/text/issues/279 and this https://github.com/haskell/text/issues/273 are the source issues. Honestly, the fact that lower version of `text` is for newer version of `ghc` is just riddiculous. I'll try to adjust version bounds to make Headroom able to compile under both 8.8 and 8.10.

**Comment by kozross** [comment]
It's strange, I agree. The only reason I knew about it was because it bit me when porting some libraries to 8.10 as well.

**Comment by vaclavsvejcar** [comment]
So I dropped the actually unnecessary dependency on `text` and also removed the version upper bounds restriction from generated `headroom.cabal`. It's released as [headroom-0.2.1.1](http://hackage.haskell.org/package/headroom-0.2.1.1) on Hackage and it builds fine for me with Cabal 3 & GHC 8.10.1, can you please confirm it works for you as well?

**Comment by kozross** [comment]
Can confirm this builds and works.

**Comment by vaclavsvejcar** [comment]
Great, thanks! Btw I'd like to add list of open source projects that uses Headroom to README, so if you plan to use Headroom for any your project, let me know and I can add the link :)
