### ISSUE TITLE
Add version option

### ISSUE THREAD

**Issue by vrom911** [vaclavsvejcar/headroom#64]
Hey there,

Thanks again for a wonderful project! 🤗 
I am using it currently to update all my copyrights, this is an extremely useful tool!

I noticed, that the `--version` option is missing, so what do you think about adding it?
I see that the version info is provided in the `--help`, which is great! Though I think that the special option for that would be also convenient.

**Comment by vaclavsvejcar** [comment]
Hello,

first of all, thanks for your kind words, I'm happy that this tool helps someone. Speaking about the option, it's great idea, I'll add it to next version.

**Comment by vaclavsvejcar** [comment]
@vrom911 So I added two more options, `--version` that displays version info and `--numeric-version` that prints out version number only (can be useful for some programmatic version comparison).

```
$ headroom --version
headroom, v0.4.0.0 :: https://github.com/vaclavsvejcar/headroom

$ headroom --numeric-version
0.4.0.0
```

**Comment by vrom911** [comment]
Wow, that's a really neat idea! Thanks so much for such a swift work on this feature! 🙌🏼

**Comment by vaclavsvejcar** [comment]
You're welcome, I'm closing this now and it will be part of the [v0.4.0.0](https://github.com/vaclavsvejcar/headroom/milestone/10) release 🙂
